services:
  - type: web
    name: inzulink
    runtime: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn InzuLink.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: inzulink-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"

databases:
  - name: inzulink-db
    plan: free
    databaseName: inzulink
    user: inzulink

